from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .scholar import *
from .vanilla_agent import *
from .my_scholar import *
from .my_web_summarizer import *
from .pitch_deck_assist import *
